// angular/routing/src/app/components/shoppingform.component.ts
import {Component} from '@angular/core';
import {ShoppingItem} from '../models/shoppingitem.model';
import {ShoppingService} from '../services/shoppingservice.service';

@Component({
	selector:"shoppingform",
	templateUrl:"./shoppingform.component.html"
})
export class ShoppingForm {
	
	shoppingItem:ShoppingItem = new ShoppingItem("",0,0,0);
	
	constructor(private _shoppingService:ShoppingService) {}
	
	addToList() {
		this._shoppingService.addToList(this.shoppingItem);
		this.shoppingItem = new ShoppingItem("",0,0,0);
	}	
}
<form (ngSubmit)="addToList()" #shoppingform="ngForm">
	<label for="type">Type:</label>
	<input type="text"
			id="type"
			name="type"
			[(ngModel)]="shoppingItem.type"/>
	<br/>
	<label for="count">Count:</label>
	<input type="number"
			id="count"
			name="count"
			[(ngModel)]="shoppingItem.count"/>
	<br/>
	<label for="price">Price:</label>
	<input type="number"
			id="price"
			name="price"
			step="0.01"
			[(ngModel)]="shoppingItem.price"/>
	<br/>
	<input type="submit" value="Add"/>
</form>

// react/hooks/usestate-hook/src/ShoppingForm.js
import React,{useState} from 'react';

const ShoppingForm = ({addToList}) => {
	
	const [item,setItem] = useState({
		type:"",
		price:0,
		count:0
	})
	
	const onChange = (event) => {
		setItem({
			...item,
			[event.target.name]:event.target.value
		})
	}
	
	const onSubmit = (event) => {
		event.preventDefault();
		addToList(item);
		setItem({
			type:"",
			price:0,
			count:0			
		})
	}
	
	return(
		<form onSubmit={onSubmit}>
			<label htmlFor="type">Type:</label>
			<input type="text"
					name="type"
					onChange={onChange}
					value={item.type}/>
			<br/>
			<label htmlFor="count">Count:</label>
			<input type="number"
					name="count"
					onChange={onChange}
					value={item.count}/>
			<br/>
			<label htmlFor="price">Price:</label>
			<input type="number"
					name="price"
					onChange={onChange}
					value={item.price}/>
			<br/>			
			<button type="submit">Add</button>
		</form>
	)
}

export default ShoppingForm;
