// react/hooks/usereducer-hook/src/ShoppingList.js
import React from 'react';

const ShoppingList = ({list,removeFromList}) => {
	
	let items = list.map((item) => {
		return (<tr key={item.id}>
					<td>{item.type}</td>
					<td>{item.count}</td>
					<td>{item.price}</td>
					<td><button onClick={() => removeFromList(item.id)}>Remove</button></td>
				</tr>)
	})
	return(
		<table>
			<thead>
				<tr>
					<th>Type</th>
					<th>Count</th>
					<th>Price</th>
					<th>Remove</th>
				</tr>
			</thead>
			<tbody>
			{items}
			</tbody>
		</table>
	)
}

export default ShoppingList;

// angular/routing/src/app/components/shoppinglist.component.ts
import {Component,OnInit} from '@angular/core';
import {ShoppingItem} from '../models/shoppingitem.model';
import {ShoppingService} from '../services/shoppingservice.service';

@Component({
	selector:"shoppinglist",
	templateUrl:"./shoppinglist.component.html"
})
export class ShoppingList implements OnInit{
	

	shoppingList:ShoppingItem[] = [];
	
	constructor(private _shoppingService:ShoppingService) {}
	
	ngOnInit() {
		this.getList();
	}
	
	getList() {
		this.shoppingList = this._shoppingService.getList()
	}
	
	
	removeFromList(idx:number) {
		this._shoppingService.removeFromList(idx);
		this.getList();
	}
}
<table>
	<thead>
		<tr>
			<th>Type</th>
			<th>Count</th>
			<th>Price</th>
			<th>Remove</th>
		</tr>
	</thead>
	<tbody>
		<tr *ngFor="let item of shoppingList;let idx=index">
			<td>{{item.type}}</td>
			<td>{{item.count}}</td>
			<td>{{item.price}}</td>
			<td><button (click)="removeFromList(idx)">Remove</button></td>
		</tr>
	</tbody>
</table>
